version: '3'
services:
  postgres:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  web:
    build: .
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PORT: '5432'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/case-manager-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
volumes:
  db-data: null